version: '3'

services:
  testdb:
    image: mysql:latest
    container_name: cmsdb_test
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: mostafa
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cust_eng_test
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}"
        ]
      timeout: 20s
      retries: 10
  db:
    image: mysql:latest
    container_name: cmsdb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}"
        ]
      timeout: 20s
      retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cmsweb
    environment:
      DBNAME: ${DB_NAME}
      DBUSER: ${DB_USER}
      DBPASSWORD: ${DB_PASSWORD}
      DBHOST: db
      DBPORT: 3306

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566-4599:4566-4599" # ports of the different services
      - "9000:9000"
    environment:
      - SERVICES=sqs # a list of desired services you want to use.
      - DEFAULT_REGION=us-east-1 # This is the region where your localstack mocks to be running
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
