FROM golang:1.19-alpine

WORKDIR /app

RUN apk add build-base
RUN go install github.com/rubenv/sql-migrate/...@latest

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

WORKDIR /app/cmd/web

RUN go env -w GO111MODULE=auto
RUN go build -o cmsapp



EXPOSE 8080
CMD ["./cmsapp"]