version: '3'

services:
  db:
    image: mysql:latest
    container_name: cmsdb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: ${DBNAME}
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DBPASSWORD}"
        ]
      timeout: 20s
      retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cmsweb
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBHOST: db
      DBPORT: 3306

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  # wait-for-db:
  #   image: atkrad/wait4x
  #   container_name: dummy
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: tcp db:3306 -t 30s -i 250ms
