development:
    dialect: mysql
    datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true
    dir: .
    table: migrations

test:
    dialect: mysql
    datasource: ${DB_TEST_USER}:${DB_TEST_PASSWORD}@tcp(${DB_TEST_HOST}:${DB_TEST_PORT})/${DB_TEST_NAME}?parseTime=true
    dir: .
    table: migrations
